### ISSUE TITLE
Friendlier UI for requestSignPayload

### ISSUE THREAD

**Issue by hyperknot** [kukai-wallet/kukai#204]
I am trying to authenticate users for a backend API using Beacon SDK.  From what I found out, the only way to do this is to use `requestSignPayload()` in taquito. My problem is that Kukai wallet shows a very scary UI and even asks for the account password when doing this. It's so scary that I believe no user would ever log in like this, thus basically making this feature unusable.

Temple, Air Gap and Spire does not make such "danger zone" warnings, they just ask for confirmation.

**Comment by hyperknot** [comment]
See related discussion: https://github.com/ecadlabs/taquito/issues/1173

**Comment by hyperknot** [comment]
I've run into a similar but much friendlier sign screen when using Tezos Profiles. Could this one be used to sign a message as well? If so, which function triggers this dialog?
![Kukai 2021-11-15 20-06-30](https://user-images.githubusercontent.com/494223/141839734-de3b1be5-c06b-4da9-b8ac-6178211d024b.png)

**Comment by hyperknot** [comment]
OK, I found it, it's the same function and decides the UI based on a regex:
https://github.com/kukai-wallet/kukai/blob/99602844898993e3342c7675ca3472b97f8d7323/src/app/services/input-validation/input-validation.service.ts#L141

Basically if the message fits this regex then it shows a nice dialog?

Would it be possible to remove the password prompt when signing a message and not an expression? Temple and AirGap wallet doesn't ask for passwords.

**Comment by klassare** [comment]
Micheline expressions can be applied on-chain and it can therefore be potentially dangerous for a user to sign a Micheline expression that's not human understandable. The "Tezos Signed Message: " prefix indicate that the message will only be used off-chain, and Kukai will therefore not show a warning when it sees that prefix. To protect against off-chain replay-attacks it's also advised that you include a domain (dapp name or url), purpose (e.g. authentication) and nonce (e.g. timestamp) in the message.

Password prompt is currently needed for all signing in Kukai, since the private key isn't stored in plaintext.

**Comment by hyperknot** [comment]
Thank you for the clarification. So you are saying that even when starting with 0501 it doesn't mean it's safe, there could still be security concerns about it? 

I was looking for where is this `Tezos Signed Message: ` standard specified, and came to the conclusion that it's basically nowhere, and right now only Kukai implements it, the other wallets display the encoded version.

I'm a newcomer to the Tezos ecosystem, what would you recommend, how to make this `Tezos Signed Message: ` + the regex you use into a more accepted format?

**Comment by hyperknot** [comment]
Update: I see that both Kukai and Temple wallet implements it, Temple checks for `signingType: SigningType.MICHELINE` while Kukai also displayed it for RAW.

I've also been pointed to this document, implementing this "standard":
https://docs.google.com/document/d/1ZgA7mZNrWl1YZ0snzjiFw1ahyXjvWFS1GvU5-caUDCE/view

**Comment by klassare** [comment]
Yes, we are following the informal standard specified in that document. It was mean as a temporary solution until we had fully domain separated message signing. Noop-based message signing is now possible and it doesn't require any prefix, but it's not yet supported by any wallets afaik.

**Comment by hyperknot** [comment]
Thanks for the explanation. I guess the password prompt is a design decision, to never store the private key decrypted in memory? It'd make a "Connect" or login flow a bit more user friendly if "human readable" message signing didn't require a password prompt, but I understand if this is a design decision.

**Comment by hyperknot** [comment]
Just for reference, here is how OpenSea's login look like with Metamask. I think it's quite nice here that they can say that no password is required.

![MetaMask Notification 2021-11-15 17-25-59](https://user-images.githubusercontent.com/494223/141818460-832a62bf-452d-487f-80d9-0f9cf1ed0af8.png)

**Comment by klassare** [comment]
I agree that it would be convenient to not prompt the user for password when signing a message. But it would require changes in our key management since we don't store the private key unencrypted in memory. We have been conservative as a precaution against XSS attacks. It's possible we will revise the key management after we have hardened the wallet in other ways.

**Comment by hyperknot** [comment]
Thanks a lot for the answers, I think everything has been answered, I'm closing this issue! Keep up the good work!
