### ISSUE TITLE
Kukai wallet

### ISSUE THREAD

**Issue by Sumeyrayucee** [kukai-wallet/kukai#247]
i logged out of my wallet, when i tried to import again, a new wallet was created and my tokens, nft accounts remained there.  I'm confused what to do, I'm doing everything right but I can't import it.

**Comment by tezit** [comment]
If you are importing seed words, there is an optional field "passphrase" which acts like a secret 25th word. If you created this wallet in Kukai, then the seed words were used with a blank passphrase to generate your account. But if you later re-imported that seed and added a passphrase then that passphrase is critical to remember in order to access it via any future imports.

**Comment by Sumeyrayucee** [comment]
I solved the problem. Thank you for your feedback.


24 Oca 2022 Pzt 06:10 tarihinde tezit ***@***.***> şunu yazdı:

**Comment by Sumeyrayucee** [comment]
Hey! I don't understand?

4 Şub 2022 Cum 11:33 tarihinde Klas Harrysson ***@***.***>
şunu yazdı:
