### ISSUE TITLE
Operation failed when tried to withdraw from Chrome browser(Using Kukai website) 

### ISSUE THREAD

**Issue by Cryptot86** [kukai-wallet/kukai#29]
Hi, 
I am getting an error message as "Unknown error when tried to withdraw from Kukai web wallet" 

can you please help ? 

Thanks.

**Comment by klassare** [comment]
Thank you for reporting this issue.

What OS are you using? Do you use some kind of adblocker or VPN tunnel?

**Comment by Cryptot86** [comment]
Hi, 

I am using Windows 10 and I am not using any adblocker or VPN. 

I have tried in 3 different browsers (IE, Brave & Chrome) but getting the same error message.

**Comment by klassare** [comment]
Would need some details about the transaction in order to troubleshoot this more efficiently. If you could provide me with the address for the sender and receiver together with the amount and fee it would really make it easier to pin down the problem. You could send it in an email to klassare@gmail.com if you want.

**Comment by klassare** [comment]
Based on the provided transaction data, the error was traced back to an invalid reveal operation. This caused by a bug in the code affecting contract invocations for wallets who had their manager account emptied before the Babylon update. This issue have now been [resolved](https://github.com/kukai-wallet/kukai/commit/f9d7d0dae4c5b2ed296196e201a48c0d6c61b33b). Thank you for helping to improve the Kukai wallet!

**Comment by Cryptot86** [comment]
Thanks for the quick response and fix, it works fine now.
