### ISSUE TITLE
Use bigger gas limit for pkh2pkh txs

### ISSUE THREAD

**Issue by roccomuso** [kukai-wallet/kukai#48]
https://github.com/kukai-wallet/kukai/blob/1ea7fa9896edc0f9df181d449840f87852fb6893/src/app/components/send/send.component.ts#L29

Can this gas limit be used as upper limit also for pkh2pkh or there's risk to incur in some kind of error?

**Comment by klassare** [comment]
You will only get an error if the gas limit is lower than the gas usage. Just be aware that the gas limit will affect the fee. Having a higher gas limit than needed will result in users having to pay higher fees than necessary. Kukai doesn't set the limits in this static way anymore for transactions (simulation based since 1.8). That's in preparation for generic contract invocation and a way to optimize the fees further.
